language: go
go:
    - tip
sudo: false
notifications:
    email: false

install:
  - go get github.com/codegangsta/cli
  - go get github.com/Sirupsen/logrus
  - go get github.com/metaleap/go-xsd-pkg/thearchitect.co.uk/schemas/rss-2_0.xsd_go
